local ADDON_NAME, ns = ...
local ToastyClassChores = ns.Addon

local config = {
    name = "Toasty Class Chores",
    handler = ToastyClassChores,
    type = "group",
    args = {
        uiLock = {
            type = "execute",
            name = "Toggle Frame Locks",
            func = "ToggleFrameLock",
            desc = "/tcc lock"
        },
        shadowform = {
            type = "group",
            name = "Shadowform",
            args = {
                shadowformTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    desc = nil,
                    get = function() return ToastyClassChores.db.profile.shadowformTracking end,
                    set = "SetShadowformTracking",
                    width = "full",
                },
                shadowformIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.shadowformIconSize end,
                    set = "SetShadowformIconSize",
                },
                shadowformOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.shadowformOpacity end,
                    set = "SetShadowformOpacity",
                },
                shadowformInCombatOnly = {
                    type = "toggle",
                    name = "In Combat Only",
                    get = function() return ToastyClassChores.db.profile.shadowformInCombatOnly end,
                    set = "SetShadowformInCombatOnly",
                    width = "full",
                    order = -3,
                },
                shadowformInstanceOnly = {
                    type = "toggle",
                    name = "Only Show in Instances",
                    get = function() return ToastyClassChores.db.profile.shadowformInstanceOnly end,
                    set = "SetShadowformInstanceOnly",
                    width = "full",
                    order = -2,
                },
                shadowformNoLegacy = {
                    type = "toggle",
                    name = "Hide in Legacy Instances",
                    desc = "Hides frame whenever legacy loot rules are active",
                    get = function() return ToastyClassChores.db.profile.shadowformNoLegacy end,
                    set = "SetShadowformNoLegacy",
                    width = "full",
                    order = -1,
                },
            }
        },
        raidBuff = {
            type = "group",
            name = "Raid Buffs",
            args = {
                raidBuffTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.raidBuffTracking end,
                    set = "SetRaidBuffTracking",
                    width = "full",
                    order = 1,
                },
                raidBuffSecretDisclaimer = {
                    type = "description",
                    name = "Manually removing your raid buff or another player applying your raid buff while secrets are active will not register until secrets deactivate.",
                    order = 2,
                },
                raidBuffIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.raidBuffIconSize end,
                    set = "SetRaidBuffIconSize",
                },
                raidBuffOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.raidBuffOpacity end,
                    set = "SetRaidBuffOpacity",
                },
                raidBuffEarlyWarning = {
                    type = "range",
                    name = "Early Warning",
                    desc = "Time in minutes before expiration at which the alert appears. NOTE: This feature is experimental and may have missed an edge case, please report any bugs!",
                    min = 0,
                    max = 60,
                    step = 1,
                    get = function() return ToastyClassChores.db.profile.raidBuffEarlyWarning end,
                    set = "SetRaidBuffEarlyWarning",
                    order = 103
                }
            }
        },
        pets = {
            type = "group",
            name = "Pets",
            args = {
                petsTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.petsTracking end,
                    set = "SetPetsTracking",
                    width = "full"
                },
                petsIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.petsIconSize end,
                    set = "SetPetsIconSize",
                },
                petsOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.petsOpacity end,
                    set = "SetPetsOpacity",
                },
                petsInstanceOnly = {
                    type = "toggle",
                    name = "Only Show in Instances",
                    get = function() return ToastyClassChores.db.profile.petsInstanceOnly end,
                    set = "SetPetsInstanceOnly",
                    width = "full",
                    order = -2,
                },
                petsNoLegacy = {
                    type = "toggle",
                    name = "Hide in Legacy Instances",
                    desc = "Hides frame whenever legacy loot rules are active",
                    get = function() return ToastyClassChores.db.profile.petsNoLegacy end,
                    set = "SetPetsNoLegacy",
                    width = "full",
                    order = -1,
                }
            }
        },
        druidForms = {
            type = "group",
            name = "Druid Forms",
            args = {
                druidFormsTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.druidFormsTracking end,
                    set = "SetDruidFormsTracking",
                    width = "full",
                },
                druidFormsIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.druidFormsIconSize end,
                    set = "SetDruidFormsIconSize",
                },
                druidFormsOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.druidFormsOpacity end,
                    set = "SetDruidFormsOpacity",
                },
                druidFormsAlwaysShow = {
                    type = "toggle",
                    name = "Always Show Form",
                    desc = "Stop the frame from hiding while in the 'correct' form",
                    get = function() return ToastyClassChores.db.profile.druidFormsAlwaysShow end,
                    set = "SetDruidFormsAlwaysShow",
                    width = "full",
                    order = 101,
                },
                druidFormsIgnoreTravel = {
                    type = "toggle",
                    name = "Ignore Travel Form",
                    get = function() return ToastyClassChores.db.profile.druidFormsIgnoreTravel end,
                    set = "SetDruidFormsIgnoreTravel",
                    width = "full",
                    order = 102,
                },
                druidFormsInCombatOnly = {
                    type = "toggle",
                    name = "In Combat Only",
                    get = function() return ToastyClassChores.db.profile.druidFormsInCombatOnly end,
                    set = "SetDruidFormsInCombatOnly",
                    width = "full",
                    order = 103,
                },
                druidFormsInstanceOnly = {
                    type = "toggle",
                    name = "Only Show in Instances",
                    get = function() return ToastyClassChores.db.profile.druidFormsInstanceOnly end,
                    set = "SetDruidFormsInstanceOnly",
                    width = "full",
                    order = -2,
                },
                druidFormsNoLegacy = {
                    type = "toggle",
                    name = "Hide in Legacy Instances",
                    desc = "Hides frame whenever legacy loot rules are active",
                    get = function() return ToastyClassChores.db.profile.druidFormsNoLegacy end,
                    set = "SetDruidFormsNoLegacy",
                    width = "full",
                    order = -1,
                }
            }
        },
        warriorStances = {
            type = "group",
            name = "Warrior Stances",
            args = {
                warriorStancesTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.warriorStancesTracking end,
                    set = "SetWarriorStancesTracking",
                    width = "full"
                },
                warriorStancesIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.warriorStancesIconSize end,
                    set = "SetWarriorStancesIconSize",
                },
                warriorStancesOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.warriorStancesOpacity end,
                    set = "SetWarriorStancesOpacity",
                },
                warriorStancesProtShowsBattle = {
                    type = "toggle",
                    name = "Show Battle Stance for Prot",
                    width = "full",
                    get = function() return ToastyClassChores.db.profile.warriorStancesProtShowsBattle end,
                    set = "SetProtShowsBattle",
                    order = -2,
                },
                warriorStancesProtShowsDef = {
                    type = "toggle",
                    name = "Show Defensive Stance for Prot",
                    width = "full",
                    get = function() return ToastyClassChores.db.profile.warriorStancesProtShowsDef end,
                    set = "SetProtShowsDef",
                    order = -1,
                },
            }
        },
        paladinAuras = {
            type = "group",
            name = "Paladin Auras",
            args = {
                paladinAurasTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.paladinAurasTracking end,
                    set = "SetPaladinAurasTracking",
                    width = "full",
                },
                paladinAurasIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.paladinAurasIconSize end,
                    set = "SetPaladinAurasIconSize",
                },
                paladinAurasOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.paladinAurasOpacity end,
                    set = "SetPaladinAurasOpacity",
                },
                paladinAurasAlwaysShow = {
                    type = "toggle",
                    name = "Show Devotion Aura",
                    get = function() return ToastyClassChores.db.profile.paladinAurasAlwaysShow end,
                    set = "SetPaladinAurasAlwaysShow",
                    width = "full",
                    order = 101,
                },
                paladinAurasInCombatOnly = {
                    type = "toggle",
                    name = "In Combat Only",
                    get = function() return ToastyClassChores.db.profile.paladinAurasInCombatOnly end,
                    set = "SetPaladinAurasInCombatOnly",
                    width = "full",
                    order = 102,
                },
                paladinAurasInstanceOnly = {
                    type = "toggle",
                    name = "Only Show in Instances",
                    get = function() return ToastyClassChores.db.profile.paladinAurasInstanceOnly end,
                    set = "SetPaladinAurasInstanceOnly",
                    width = "full",
                    order = -2,
                },
                paladinAurasNoLegacy = {
                    type = "toggle",
                    name = "Hide in Legacy Instances",
                    desc = "Hides frame whenever legacy loot rules are active",
                    get = function() return ToastyClassChores.db.profile.paladinAurasNoLegacy end,
                    set = "SetPaladinAurasNoLegacy",
                    width = "full",
                    order = -1,
                },
            }
        },
        sacrificeGrimoire = {
            type = "group",
            name = "Grimoire of Sacrifice",
            args = {
                sacrificeGrimoireTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.sacrificeGrimoireTracking end,
                    set = "SetSacrificeGrimoireTracking",
                    width = "full",
                },
                sacrificeGrimoireIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.sacrificeGrimoireIconSize end,
                    set = "SetSacrificeGrimoireIconSize",
                },
                sacrificeGrimoireOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.sacrificeGrimoireOpacity end,
                    set = "SetSacrificeGrimoireOpacity",
                },
            },
        },
        roguePoisons = {
            type = "group",
            name = "Rogue Poisons",
            args = {
                roguePoisonsTracking = {
                    type = "toggle",
                    name = "Enable Tracking",
                    get = function() return ToastyClassChores.db.profile.roguePoisonsTracking end,
                    set = "SetRoguePoisonsTracking",
                    width = "full",
                    order = 1,
                },
                roguePoisonsSecretDisclaimer = {
                    type = "description",
                    name = "Manually removing poisons while secrets are active will not register until secrets deactivate.",
                    order = 2,
                },
                roguePoisonsIconSize = {
                    type = "range",
                    name = "Icon Size",
                    softMax = 200,
                    desc = "Input number for larger icons",
                    get = function() return ToastyClassChores.db.profile.roguePoisonsIconSize end,
                    set = "SetRoguePoisonsIconSize",
                },
                roguePoisonsOpacity = {
                    type = "range",
                    name = "Opacity",
                    min = 0,
                    max = 1,
                    get = function() return ToastyClassChores.db.profile.roguePoisonsOpacity end,
                    set = "SetRoguePoisonsOpacity",
                },
                roguePoisonsEarlyWarning = {
                    type = "range",
                    name = "Early Warning",
                    desc = "Time in minutes before expiration at which the alert appears. NOTE: This feature is experimental and may have missed an edge case, please report any bugs!",
                    min = 0,
                    max = 60,
                    step = 1,
                    get = function() return ToastyClassChores.db.profile.roguePoisonsEarlyWarning end,
                    set = "SetRoguePoisonsEarlyWarning",
                    order = 103
                }
            }
        },
    },
}

local defaults = {
    profile = {
        frameLock = true,
        debug = false,
        shadowformTracking = true,
        shadowformIconSize = 100,
        shadowformInCombatOnly = false,
        shadowformInstanceOnly = false,
        shadowformNoLegacy = false,
        shadowformOpacity = 1,
        shadowformLocation = {
            xPos = 0,
            yPos = 55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        raidBuffTracking = true,
        raidBuffIconSize = 100,
        raidBuffOpacity = 1,
        raidBuffEarlyWarning = 0,
        raidBuffLocation = {
            xPos = 0,
            yPos = -55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        petsTracking = true,
        petsIconSize = 100,
        petsInstanceOnly = false,
        petsNoLegacy = false,
        petsOpacity = 1,
        petsLocation = {
            xPos = 0,
            yPos = 55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        druidFormsTracking = true,
        druidFormsIconSize = 100,
        druidFormsInCombatOnly = false,
        druidFormsIgnoreTravel = false,
        druidFormsInstanceOnly = false,
        druidFormsNoLegacy = false,
        druidFormsOpacity = 1,
        druidFormsLocation = {
            xPos = 0,
            yPos = 55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        warriorStancesAlwaysShow = false,
        warriorStancesTracking = true,
        warriorStancesIconSize = 100,
        warriorStancesProtShowsBattle = false,
        warriorStancesProtShowsDef = true,
        warriorStancesOpacity = 1,
        warriorStancesLocation = {
            xPos = 0,
            yPos = 55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        paladinAurasTracking = true,
        paladinAurasIconSize = 100,
        paladinAurasInCombatOnly = false,
        paladinAurasInstanceOnly = false,
        paladinAurasNoLegacy = false,
        paladinAurasOpacity = 1,
        paladinAurasLocation = {
            xPos = 0,
            yPos = 55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        sacrificeGrimoireTracking = true,
        sacrificeGrimoireIconSize = 100,
        sacrificeGrimoireOpacity = 1,
        sacrificeGrimoireLocation = {
            xPos = 0,
            yPos = -55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
        roguePoisonsTracking = true,
        roguePoisonsIconSize = 100,
        roguePoisonsOpacity = 1,
        roguePoisonsEarlyWarning = 0,
        roguePoisonsLocation = {
            xPos = 0,
            yPos = -55,
            parentAnchorPoint = "CENTER",
            frameAnchorPoint = "CENTER",
        },
    },
}

local characterDefaults = {
    profile = {
        class = "",
        remainingLethalPoisonTime = nil,
        remainingNonLethalPoisonTime = nil,
        remainingLethalPoisonTimeAssa = nil,
        remainingNonLethalPoisonTimeAssa = nil,
        remainingRaidBuffTime = nil
    },
}

ToastyClassChores.config = config
ToastyClassChores.characterDefaults = characterDefaults
ToastyClassChores.defaults = defaults
